vim.g.mapleader = ' '
require("option")
require("keymap")
require("plugin")
require("autocmd")
require("config.lualine")
require("config.rose-pine")
require("config.nvim-tree")
require("config.ultisnips")
require("config.toggleterm")
require("config.tree-sitter")
